version: '2'
services:
  mysqlsecutiry:
    image: mysql:5.7.27
    restart: always

  mongo:
    image: mongo:4.4.6
    restart: always

  redis:
    image: redis:5.0.5-alpine3.10
    restart: always

  redis5:
    image: redis:5.0.5-alpine3.10

  mysql:
    image: mysql:5.5.62

  securityv2:
    image: mariadb:10.3.15
