version: '3.2'
services:
  #Node
  node:
    container_name: Node-MS-CRM
    build:
        context: ./
        dockerfile: ./ms_crm/Dockerfile
    restart: always
    env_file:
      - ms_crm/ms_crm.env
    volumes:
      - ../callcenter0_ms_crm:/opt/app
      - /opt/app/node_modules/
    ports:
      - 3500:3000
    networks:
      deploy_microvoz_net:
        ipv4_address: 173.17.0.26

networks:
  deploy_microvoz_net:
    external: true
