version: '3'
services:
    db_replica_1:
        container_name: ${DB_SERVICE_NAME}-1
        image: ${DB_SERVICE_NAME}-1"
        build: ./rs0-1
        ports:
        - ${DB_REPLICA_1_PORT}:27017
        volumes:
        - ../../../data/${DB_SERVICE_NAME}-1/db:/data/db
        - ../../../logs/${DB_SERVICE_NAME}-1:/var/log/mongodb/db
        - ../../../backup/${DB_SERVICE_NAME}-1:/var/log/mongodb/backup
        - ../../../mongo-backup:/opt/mongo-backup
    db_replica_2:
        container_name: ${DB_SERVICE_NAME}-2
        image: "mongo:4.4.6"
        command: --replSet rs0 --oplogSize 128
        ports:
        - ${DB_REPLICA_2_PORT}:27017
        volumes:
        - ../../../data/${DB_SERVICE_NAME}-2/db:/data/db
    db_repica_3:
        container_name: ${DB_SERVICE_NAME}-3
        image: "mongo:4.4.6"
        command: --replSet rs0 --oplogSize 128
        ports:
        - ${DB_REPLICA_3_PORT}:27017
        volumes:
        - ../../../data/${DB_SERVICE_NAME}-3/db:/data/db
        
    db_replica_setup:
        image: ${DB_SERVICE_NAME}-setup
        container_name: ${DB_SERVICE_NAME}-setup
        build: ./setup