version: '3'
services:
    quasar2_client:
        container_name: quasar2_client
        build:
            context: ./
            dockerfile: ./Dockerfile
        restart: always
        volumes:
            - ../../../client/quasar2: opt/app
        ports:
        - ${QUASAR2_CLIENT_PORT}:8080